version: "3.7"
services:
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network

  nginx:
    build: ngnix
    restart: always
    ports:
      - 80:80
    networks:
      - flask_network

networks:
  flask_network: