version: "3.7"
services:
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    networks:
      - flask_network

  nginx:
    build: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/conf:ro
      - ./ssl:/etc/nginx/conf.d/ssl:ro
    networks:
      - flask_network

networks:
  flask_network: